name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: "Remove root package"
        run: rm -rf node_modules package.json package-lock.json apps/server/node_modules

      ## Enable this to  install external npm packages ignored by esbuild
      # - name: "Install production dependencies"
      #   working-directory: apps/server
      #   run: npm install --omit=dev

      # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          clean: true
          app-name: "aipx"
          slot-name: "Production"
          package: ./apps/server

      - name: azure logout
        run: az logout
        if: always()
